# Builds prod and dev builds
name: Build lui

on:
  push:
    branches:
      - master
    paths:
      - 'package.json'
  pull_request:
    branches:
      - master
    paths:
      - 'package.json'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build lui
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      
      - name: Install dependencies
        run: bun install
      
      - name: Build lui
        run: |
          git fetch origin dist
          bun run build
      - name: Commit artifacts and purge cache
        if: github.ref == 'refs/heads/master'
        run: |
          export LUIVERSION=$(bun -e "console.log(require('./package.json').version)")
          export LUIVERSION_MAJOR=$(bun -e "console.log(require('./package.json').version.split('.')[0])")
          mv dist /tmp/lui-dist
          git checkout dist
          mv /tmp/lui-dist/* ./
          git add .
          git config user.name github-actions
          git config user.email github-actions@github.com
          git diff-index --quiet HEAD || git commit -m "v$LUIVERSION"
          git push
          git tag -f "v$LUIVERSION"
          git push -f --tags
          for i in *.js; do curl -s "https://purge.jsdelivr.net/gh/L3P3/lui@$LUIVERSION_MAJOR/$i" > /dev/null; done
